title: DataPhilly # your name (or website title) here
logo: "/images/DataPhillyLogo_Final-01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  DataPhilly is a community run group for anyone interested in gaining insights from data. 
  <br><br>
  Topics include (but are not limited to) predictive analytics, applied machine learning, big data, data warehousing and data science. 
  <br><br>
  <a href="https://www.meetup.com/DataPhilly/">DataPhilly Meetup</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
